-- Run this in your Supabase SQL Editor

-- 1. Create the 'careers' table
CREATE TABLE IF NOT EXISTS public.careers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    stream TEXT NOT NULL,
    roadmap_data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.careers ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy that allows anonymous read access
CREATE POLICY "Allow public read-only access to careers" ON public.careers FOR SELECT USING (true);
